/home/orion-lab/miniconda3/envs/py310/bin/python /home/orion-lab/repos/genomic-FM/compare-tokenizers.py gt
/home/orion-lab/miniconda3/envs/py310/bin/python /home/orion-lab/repos/genomic-FM/compare-tokenizers.py gt
/home/orion-lab/miniconda3/envs/py310/bin/python /home/orion-lab/repos/genomic-FM/compare-tokenizers.py hyena
/home/orion-lab/miniconda3/envs/py310/bin/python /home/orion-lab/repos/genomic-FM/compare-tokenizers.py hyena
/home/orion-lab/miniconda3/envs/py310/bin/python /home/orion-lab/repos/genomic-FM/compare-tokenizers.py 3mer
/home/orion-lab/miniconda3/envs/py310/bin/python /home/orion-lab/repos/genomic-FM/compare-tokenizers.py 3mer
/home/orion-lab/miniconda3/envs/py310/bin/python /home/orion-lab/repos/genomic-FM/compare-tokenizers.py 6mer
/home/orion-lab/miniconda3/envs/py310/bin/python /home/orion-lab/repos/genomic-FM/compare-tokenizers.py 6mer
/home/orion-lab/miniconda3/envs/py310/bin/python /home/orion-lab/repos/genomic-FM/compare-tokenizers.py dnab
/home/orion-lab/miniconda3/envs/py310/bin/python /home/orion-lab/repos/genomic-FM/compare-tokenizers.py dnab
/home/orion-lab/miniconda3/envs/py310/bin/python /home/orion-lab/repos/genomic-FM/compare-tokenizers.py gt
/home/orion-lab/miniconda3/envs/py310/bin/python /home/orion-lab/repos/genomic-FM/compare-tokenizers.py gt
/home/orion-lab/miniconda3/envs/py310/bin/python /home/orion-lab/repos/genomic-FM/compare-tokenizers.py hyena
/home/orion-lab/miniconda3/envs/py310/bin/python /home/orion-lab/repos/genomic-FM/compare-tokenizers.py hyena
/home/orion-lab/miniconda3/envs/py310/bin/python /home/orion-lab/repos/genomic-FM/compare-tokenizers.py 3mer
/home/orion-lab/miniconda3/envs/py310/bin/python /home/orion-lab/repos/genomic-FM/compare-tokenizers.py 3mer
/home/orion-lab/miniconda3/envs/py310/bin/python /home/orion-lab/repos/genomic-FM/compare-tokenizers.py 6mer
/home/orion-lab/miniconda3/envs/py310/bin/python /home/orion-lab/repos/genomic-FM/compare-tokenizers.py 6mer
/home/orion-lab/miniconda3/envs/py310/bin/python /home/orion-lab/repos/genomic-FM/compare-tokenizers.py dnab
/home/orion-lab/miniconda3/envs/py310/bin/python /home/orion-lab/repos/genomic-FM/compare-tokenizers.py dnab
/home/orion-lab/miniconda3/envs/py310/bin/python /home/orion-lab/repos/genomic-FM/compare-tokenizers.py gt
/home/orion-lab/miniconda3/envs/py310/bin/python /home/orion-lab/repos/genomic-FM/compare-tokenizers.py gt
/home/orion-lab/miniconda3/envs/py310/bin/python /home/orion-lab/repos/genomic-FM/compare-tokenizers.py hyena
/home/orion-lab/miniconda3/envs/py310/bin/python /home/orion-lab/repos/genomic-FM/compare-tokenizers.py hyena
/home/orion-lab/miniconda3/envs/py310/bin/python /home/orion-lab/repos/genomic-FM/compare-tokenizers.py 3mer
/home/orion-lab/miniconda3/envs/py310/bin/python /home/orion-lab/repos/genomic-FM/compare-tokenizers.py 3mer
/home/orion-lab/miniconda3/envs/py310/bin/python /home/orion-lab/repos/genomic-FM/compare-tokenizers.py 6mer
/home/orion-lab/miniconda3/envs/py310/bin/python /home/orion-lab/repos/genomic-FM/compare-tokenizers.py 6mer
/home/orion-lab/miniconda3/envs/py310/bin/python /home/orion-lab/repos/genomic-FM/compare-tokenizers.py dnab
/home/orion-lab/miniconda3/envs/py310/bin/python /home/orion-lab/repos/genomic-FM/compare-tokenizers.py dnab
/home/orion-lab/miniconda3/envs/py310/bin/python /home/orion-lab/repos/genomic-FM/compare-tokenizers.py gt
/home/orion-lab/miniconda3/envs/py310/bin/python /home/orion-lab/repos/genomic-FM/compare-tokenizers.py gt
/home/orion-lab/miniconda3/envs/py310/bin/python /home/orion-lab/repos/genomic-FM/compare-tokenizers.py hyena
/home/orion-lab/miniconda3/envs/py310/bin/python /home/orion-lab/repos/genomic-FM/compare-tokenizers.py hyena
/home/orion-lab/miniconda3/envs/py310/bin/python /home/orion-lab/repos/genomic-FM/compare-tokenizers.py 3mer
/home/orion-lab/miniconda3/envs/py310/bin/python /home/orion-lab/repos/genomic-FM/compare-tokenizers.py 3mer
/home/orion-lab/miniconda3/envs/py310/bin/python /home/orion-lab/repos/genomic-FM/compare-tokenizers.py 6mer
/home/orion-lab/miniconda3/envs/py310/bin/python /home/orion-lab/repos/genomic-FM/compare-tokenizers.py 6mer
/home/orion-lab/miniconda3/envs/py310/bin/python /home/orion-lab/repos/genomic-FM/compare-tokenizers.py dnab
/home/orion-lab/miniconda3/envs/py310/bin/python /home/orion-lab/repos/genomic-FM/compare-tokenizers.py dnab
/home/orion-lab/miniconda3/envs/py310/bin/python /home/orion-lab/repos/genomic-FM/compare-tokenizers.py gt
/home/orion-lab/miniconda3/envs/py310/bin/python /home/orion-lab/repos/genomic-FM/compare-tokenizers.py gt
/home/orion-lab/miniconda3/envs/py310/bin/python /home/orion-lab/repos/genomic-FM/compare-tokenizers.py hyena
/home/orion-lab/miniconda3/envs/py310/bin/python /home/orion-lab/repos/genomic-FM/compare-tokenizers.py hyena
/home/orion-lab/miniconda3/envs/py310/bin/python /home/orion-lab/repos/genomic-FM/compare-tokenizers.py 3mer
/home/orion-lab/miniconda3/envs/py310/bin/python /home/orion-lab/repos/genomic-FM/compare-tokenizers.py 3mer
/home/orion-lab/miniconda3/envs/py310/bin/python /home/orion-lab/repos/genomic-FM/compare-tokenizers.py 6mer
/home/orion-lab/miniconda3/envs/py310/bin/python /home/orion-lab/repos/genomic-FM/compare-tokenizers.py 6mer
/home/orion-lab/miniconda3/envs/py310/bin/python /home/orion-lab/repos/genomic-FM/compare-tokenizers.py dnab
/home/orion-lab/miniconda3/envs/py310/bin/python /home/orion-lab/repos/genomic-FM/compare-tokenizers.py dnab