/home/orion-lab/miniconda3/envs/py310/bin/python /home/orion-lab/repos/genomic-FM/compare-tokenizers.py gt 1536
/home/orion-lab/miniconda3/envs/py310/bin/python /home/orion-lab/repos/genomic-FM/compare-tokenizers.py gt 1536
/home/orion-lab/miniconda3/envs/py310/bin/python /home/orion-lab/repos/genomic-FM/compare-tokenizers.py gt 1536
/home/orion-lab/miniconda3/envs/py310/bin/python /home/orion-lab/repos/genomic-FM/compare-tokenizers.py gt 1536
/home/orion-lab/miniconda3/envs/py310/bin/python /home/orion-lab/repos/genomic-FM/compare-tokenizers.py gt 1536
/home/orion-lab/miniconda3/envs/py310/bin/python /home/orion-lab/repos/genomic-FM/compare-tokenizers.py 3mer 1536
/home/orion-lab/miniconda3/envs/py310/bin/python /home/orion-lab/repos/genomic-FM/compare-tokenizers.py 3mer 1536
/home/orion-lab/miniconda3/envs/py310/bin/python /home/orion-lab/repos/genomic-FM/compare-tokenizers.py 3mer 1536
/home/orion-lab/miniconda3/envs/py310/bin/python /home/orion-lab/repos/genomic-FM/compare-tokenizers.py 3mer 1536
/home/orion-lab/miniconda3/envs/py310/bin/python /home/orion-lab/repos/genomic-FM/compare-tokenizers.py 3mer 1536
