oligogenic_codon_bert:
  class: OligogenicDataWrapper
  task: classification
  Seq_length: 512
  pca_components: 16
  model_initiator_name: codon-bert
  output_size: 2


oligogenic_dnabert2:
  class: OligogenicDataWrapper
  task: classification
  Seq_length: 2048
  pca_components: 16
  model_initiator_name: dnabert2
  output_size: 2

clinvar_significance_dnabert2:
  class: ClinVarDataWrapper
  task: classification
  target: CLNSIG
  Seq_length: 2048
  pca_components: 16
  model_initiator_name: dnabert2
  output_size: 4

clinvar_significance_codon_bert:
  class: ClinVarDataWrapper
  task: classification
  target: CLNSIG
  Seq_length: 512
  pca_components: 16
  model_initiator_name: codon-bert
  output_size: 4

clinvar_disease_dnabert2:
  class: ClinVarDataWrapper
  task: classification
  target: CLNDN
  Seq_length: 2048
  pca_components: 16
  model_initiator_name: dnabert2
  output_size: 2

clinvar_disease_codon_bert:
  class: ClinVarDataWrapper
  task: classification
  target: CLNDN
  Seq_length: 512
  pca_components: 16
  model_initiator_name: codon-bert
  output_size: 2